# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

factorcpp <- function(x, levs) {
    .Call(`_occurR_factorcpp`, x, levs)
}

groupsum <- function(x, ng = 0L, g = 0L) {
    .Call(`_occurR_groupsum`, x, ng, g)
}

